
version: "2.1"
services:
  rabbitMQ_server:
    image: 'rabbitmq:3-management'
    container_name: rabbitMQ_server
    ports:
        - '5672:5672'
        - '15672:15672'
    restart: always 
  producer:
    image: /home/pes1ug19cs077/CloudHack_2/app/producer
    container_name: producer
    restart: always 
    ports:
        - '5200:5200'
    depends_on:
      - rabbitMQ_server
  ride_matching:
    image: /home/pes1ug19cs077/CloudHack_2/app/ride_matching_consumer
    container_name: ride_matching_consumer
    depends_on:
      - rabbitMQ_server
      - producer
    environment:
      - CONSUMER_ID= 1
      - PRODUCER_ADDRESS= 'localhost'
  ride_database:
    image: /home/pes1ug19cs077/CloudHack_2/app/database_consumer.py
    container_name: database_consumer 
    restart: always 
    depends_on:
      - producer
  
