# Fill in the YAML configuration for the microservices 

version: "2.1"
services:
  rabbitMQ_server:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports: 
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
  producer:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    restart: unless-stopped
    ports: '15672:15672'
    depends_on:
      - rabbitMQ_server
  ride_matching:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    depends_on:
      - rabbitMQ_server
    environment:
      - CONSUMER_ID= 1
      - PRODUCER_ADDRESS = http://10.0.2.15:5200/
  ride_database:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    restart: unless-stopped
    depends_on:
      - producer
  
