version: "3.2"

services:

  rabbit_mq:

    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  producer:
    build: producer
    depends_on:
        - rabbit_mq
    ports:
        - 5200:5200
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/home/pes1ug19cs077/CloudHack_2/app/producer

  consumer1:
    build: consumer
    depends_on:
        - rabbit_mq
        - producer
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
        CONSUMER_ID: 1
        SERVER_URL: 'http://10.0.2.15:5200/new_ride_matching_consumer'
    volumes:
      - ./consumer:/home/pes1ug19cs077/CloudHack_2/app/consumer

  consumer2:
    build: consumer
    depends_on:
        - rabbit_mq
        - producer
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
        CONSUMER_ID: 2
        SERVER_URL: 'http://10.0.2.15:5200/new_ride_matching_consumer'
    volumes:
      - ./consumer:/home/pes1ug19cs077/CloudHack_2/app/consumer

  database:
    build: database
    depends_on:
        - rabbit_mq
        - producer
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./database:/home/pes1ug19cs077/CloudHack_2/app/database
volumes:
    rabbit_mqdata:
      driver: local
